name: habitly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.7
  confetti: ^0.8.0
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  logger: ^2.5.0
  table_calendar: ^3.0.9
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#01A2FF" # or any color that matches your design
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  remove_alpha_ios: true
  min_sdk_android: 21

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#01A2FF"
  image: "assets/images/splash_screen.png"
  android_12:
    image: "assets/images/splash_screen.png"
    icon_background_color: "#01A2FF"
  ios: true
  web: false
